---

- hosts: ios02 eos02
  
  tasks:
     - include_vars: 'main.yml' 
     - include_tasks: setup_copy.yml
     - include_tasks: copy_run.yml
     - include_tasks: network_get.yml
     - include_tasks: cleanup.yml
